// Assignment3/client/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <h1>UNO Multiplayer</h1>
      <p class="subtitle">Enter your name to start playing</p>
      
      <form @submit.prevent="handleLogin" class="login-form">
        <input
          v-model="playerName"
          type="text"
          placeholder="Enter your name"
          maxlength="20"
          required
          class="player-input"
          autofocus
        />
        <button type="submit" class="login-button" :disabled="!playerName.trim()">
          Play UNO
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { usePlayerStore } from '../stores/player'

const router = useRouter()
const playerStore = usePlayerStore()
const playerName = ref(playerStore.playerName || '')

function handleLogin() {
  const trimmedName = playerName.value.trim()
  if (trimmedName) {
    playerStore.setPlayerName(trimmedName)
    router.push('/lobby')
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #0f0f0f 0%, #1d1d1d 100%);
  padding: 20px;
}

.login-card {
  background: #f5f5f5;
  padding: 40px;
  border-radius: 20px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.35);
  max-width: 400px;
  width: 100%;
  text-align: center;
}

h1 {
  color: #111;
  margin-bottom: 10px;
  font-size: 2.5rem;
  font-weight: bold;
}

.subtitle {
  color: #555;
  margin-bottom: 30px;
  font-size: 1rem;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.player-input {
  padding: 15px;
  font-size: 1.1rem;
  border: 2px solid #2f2f2f;
  border-radius: 10px;
  transition: all 0.3s ease;
  background: white;
}

.player-input:focus {
  outline: none;
  border-color: #111;
  box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.15);
}

.login-button {
  padding: 15px;
  font-size: 1.2rem;
  font-weight: bold;
  color: white;
  background: #111;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.login-button:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.35);
}

.login-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>

// Assignment5/client/src/views/Login.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useServerConnection } from '../hooks/useServerConnection'

/**
 * Login page - player enters name to start
 */
export default function LoginView() {
  const navigate = useNavigate()
  const [name, setName] = useState('')
  const { isConnected, send } = useServerConnection()

  const handleLogin = () => {
    if (!name.trim()) return
    send({ type: 'set-name', name: name.trim() })
    navigate('/lobby')
  }

  return (
    <div className="login-container">
      <div className="login-card">
        <h1>UNO Multiplayer</h1>
        <p className="subtitle">Enter your name to start playing</p>
        {!isConnected && <p className="alert">Connecting to server...</p>}
        <form
          className="login-form"
          onSubmit={(e) => {
            e.preventDefault()
            handleLogin()
          }}
        >
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            type="text"
            placeholder="Enter your name"
            maxLength={20}
            required
            className="player-input"
            autoFocus
          />
          <button type="submit" className="login-button" disabled={!name.trim() || !isConnected}>
            Play UNO
          </button>
        </form>
      </div>
    </div>
  )
}
